import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Offline — InZone',
  description: 'You are currently offline.',
};

/**
 * Offline fallback. The service worker (generated by next-pwa) serves this
 * route for navigation requests that fail when the network is unavailable and
 * nothing suitable is cached. Kept dependency-free so it renders from cache.
 */
export default function OfflinePage() {
  return (
    <main
      style={{
        minHeight: '100dvh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '1rem',
        padding: '2rem',
        textAlign: 'center',
        background: '#0a0d12',
        color: '#e6e8ec',
      }}
    >
      <div
        aria-hidden="true"
        style={{
          fontSize: '3rem',
          lineHeight: 1,
          opacity: 0.9,
        }}
      >
        ⚡
      </div>
      <h1 style={{ fontSize: '1.5rem', fontWeight: 600, margin: 0 }}>
        You&apos;re offline
      </h1>
      <p style={{ maxWidth: '28rem', opacity: 0.7, margin: 0, lineHeight: 1.5 }}>
        InZone can&apos;t reach the network right now. Pages and game data you&apos;ve
        already visited are still available. Reconnect to load everything else.
      </p>
      <a
        href="/"
        style={{
          marginTop: '0.5rem',
          padding: '0.6rem 1.25rem',
          borderRadius: '0.5rem',
          border: '1px solid rgba(255,255,255,0.15)',
          color: '#e6e8ec',
          textDecoration: 'none',
          fontWeight: 500,
        }}
      >
        Try again
      </a>
    </main>
  );
}
